//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoJaJo.FoJaJoWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="FoJaJoWebService.FoJaJoWebServiceSoap")]
    public interface FoJaJoWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FoJaJo.FoJaJoWebService.Player GetPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayer", ReplyAction="*")]
        System.Threading.Tasks.Task<FoJaJo.FoJaJoWebService.Player> GetPlayerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPlayers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FoJaJo.FoJaJoWebService.Player[] GetAllPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPlayers", ReplyAction="*")]
        System.Threading.Tasks.Task<FoJaJo.FoJaJoWebService.Player[]> GetAllPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FoJaJo.FoJaJoWebService.Game[] GetAllGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGames", ReplyAction="*")]
        System.Threading.Tasks.Task<FoJaJo.FoJaJoWebService.Game[]> GetAllGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FoJaJo.FoJaJoWebService.Player[] GetPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlayers", ReplyAction="*")]
        System.Threading.Tasks.Task<FoJaJo.FoJaJoWebService.Player[]> GetPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FindFile(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindFile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> FindFileAsync(string filePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBudgetBuffer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBudgetBuffer(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBudgetBuffer", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBudgetBufferAsync(string filter);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class Player : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string emailField;
        
        private string passwordField;
        
        private int ratingField;
        
        private int totalWinsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
                this.RaisePropertyChanged("Rating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TotalWins {
            get {
                return this.totalWinsField;
            }
            set {
                this.totalWinsField = value;
                this.RaisePropertyChanged("TotalWins");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultIdField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultId {
            get {
                return this.resultIdField;
            }
            set {
                this.resultIdField = value;
                this.RaisePropertyChanged("ResultId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org")]
    public partial class Game : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int gameIDField;
        
        private string startedPlayerUsernameField;
        
        private Player startedPlayerField;
        
        private int maxNumberOfPlayersField;
        
        private string boardDimensionField;
        
        private int resultIDField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int GameID {
            get {
                return this.gameIDField;
            }
            set {
                this.gameIDField = value;
                this.RaisePropertyChanged("GameID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StartedPlayerUsername {
            get {
                return this.startedPlayerUsernameField;
            }
            set {
                this.startedPlayerUsernameField = value;
                this.RaisePropertyChanged("StartedPlayerUsername");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Player StartedPlayer {
            get {
                return this.startedPlayerField;
            }
            set {
                this.startedPlayerField = value;
                this.RaisePropertyChanged("StartedPlayer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int MaxNumberOfPlayers {
            get {
                return this.maxNumberOfPlayersField;
            }
            set {
                this.maxNumberOfPlayersField = value;
                this.RaisePropertyChanged("MaxNumberOfPlayers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BoardDimension {
            get {
                return this.boardDimensionField;
            }
            set {
                this.boardDimensionField = value;
                this.RaisePropertyChanged("BoardDimension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ResultID {
            get {
                return this.resultIDField;
            }
            set {
                this.resultIDField = value;
                this.RaisePropertyChanged("ResultID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Result Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FoJaJoWebServiceSoapChannel : FoJaJo.FoJaJoWebService.FoJaJoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoJaJoWebServiceSoapClient : System.ServiceModel.ClientBase<FoJaJo.FoJaJoWebService.FoJaJoWebServiceSoap>, FoJaJo.FoJaJoWebService.FoJaJoWebServiceSoap {
        
        public FoJaJoWebServiceSoapClient() {
        }
        
        public FoJaJoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoJaJoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoJaJoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoJaJoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FoJaJo.FoJaJoWebService.Player GetPlayer(string username) {
            return base.Channel.GetPlayer(username);
        }
        
        public System.Threading.Tasks.Task<FoJaJo.FoJaJoWebService.Player> GetPlayerAsync(string username) {
            return base.Channel.GetPlayerAsync(username);
        }
        
        public FoJaJo.FoJaJoWebService.Player[] GetAllPlayers() {
            return base.Channel.GetAllPlayers();
        }
        
        public System.Threading.Tasks.Task<FoJaJo.FoJaJoWebService.Player[]> GetAllPlayersAsync() {
            return base.Channel.GetAllPlayersAsync();
        }
        
        public FoJaJo.FoJaJoWebService.Game[] GetAllGames() {
            return base.Channel.GetAllGames();
        }
        
        public System.Threading.Tasks.Task<FoJaJo.FoJaJoWebService.Game[]> GetAllGamesAsync() {
            return base.Channel.GetAllGamesAsync();
        }
        
        public FoJaJo.FoJaJoWebService.Player[] GetPlayers() {
            return base.Channel.GetPlayers();
        }
        
        public System.Threading.Tasks.Task<FoJaJo.FoJaJoWebService.Player[]> GetPlayersAsync() {
            return base.Channel.GetPlayersAsync();
        }
        
        public string FindFile(string filePath) {
            return base.Channel.FindFile(filePath);
        }
        
        public System.Threading.Tasks.Task<string> FindFileAsync(string filePath) {
            return base.Channel.FindFileAsync(filePath);
        }
        
        public System.Data.DataSet getBudgetBuffer(string filter) {
            return base.Channel.getBudgetBuffer(filter);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBudgetBufferAsync(string filter) {
            return base.Channel.getBudgetBufferAsync(filter);
        }
    }
}
