//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public byte[] timestamp { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Company() { }
        public Company(string name)
        {
            Name = name;
        }
    }
}
